---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - namespace="robertdebock/"
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-centos-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - namespace="opensuse/" image="leap"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "IZOMU9fSW9vgikqxGNrDR3q3kPeB/PaT88L9me51VmnPPGdWEgCGoaRab/cifJ6R4gKK8cev6NF+Zu7bumaCxUJIOJtTRMNSTiXH98vAg1k5tb9+bYd0jlKP9q63Wf5UXEHEz7xObNO6XVjFkaNobSJUvpLPAKby1uITQX+pxaz98K1ur1RZlNMbk1IIsPOL/oZUlM5vDjED4Z3FTqh9fxmFZ6tnNZGlOAEZCcYgSXrdzV3j9pnIPomuF2RNEM9Qxwco8K1sDz2Fq88RCWcPsfvzBsAA5fXQQMbbm4lEQSG2V46aaXkO9enHhTtN+4jWq3awHA/NEMdzZhBC7Beye4OmifEylhagT+afSvI3ZvK4RFTKJaybqjcMH/7YrYqB+5y3Muh8ttIm9iTHGnuUHgfvib7esCwPh/PEG0kTEs17vfEgqFvmKOpUovSsEcmOBJF+le6jwhcTQnKVHHbWCxwH78nx+RX9mYvNG/Nfi21rwGoF35x4P+EogbYd+hZKdQbFKYgIefa7b6U7J/iFtn3BKjx10wOhSOQGSUfmhcplrIaPeB5p7XKSiF5v75nrcRRJZH7SySLUpU4YLR1uUrpFzfXXqiTwW6olbczPn9QH64MKB/8XZ49OAhDOt80orKAotNx2lkXBktHb0WgEfG5nW0qwBcJiDdpcQzJLHMY="
  email: false
