---
# tasks file for at
- name: install at software
  package:
    name: at
    state: present
  register: at_install_at_software
  until: at_install_at_software is succeeded
  retries: 3

- name: start and enable at software
  service:
    name: atd
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker" or at_ignore_docker
