---
# tasks file for at
- name: install software
  package:
    name: at
    state: present

- name: start and enable software
  service:
    name: atd
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
