---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: at-centos-7
    box: centos/7
  - name: at-debian-jessie64
    box: debian/jessie64
  - name: at-fedora-28-cloud-base
    box: fedora/28-cloud-base
  - name: at-opensuse-openSUSE-42-2-x86-64
    box: opensuse/openSUSE-42.2-x86_64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: goss
  lint:
    name: yamllint
