---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: at-alpine-latest
    image: alpine:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: alpine-latest
verifier:
  name: goss
  lint:
    name: yamllint
